[book]
authors = ["Howard Hu"]
language = "en"
multilingual = false
src = "src"
title = "SRE Notebook"


[output.html]
mathjax-support = true
git-repository-url = "https://github.com/cool-howard-hu/sre-notebook/tree/main"
edit-url-template = "https://github.com/cool-howard-hu/sre-notebook/tree/main{path}"